New bot command to count members in server
ADEPT-Informatique/adeptbot pull request #87
Opened 2022-12-28 05:13 UTC by Source-Dom

Je crois que le repo est à jour maintenant.

2022-12-30 08:40 UTC, Source-Dom commented
Va peut-être falloir que je change le nom de la commande pis la rajouter dans help aussi

2022-12-31 01:40 UTC, DeveloperAnonymous requested changes

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/bot_configs.py
> +import base_configs as configs
Tu devrais revert les changements de ce fichier

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/member.py
> +import base_configs as configs
Revert l'import

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/member.py
> +            raise AdeptBotException(
revert ça aussi, pour éviter un "clash de formateur"

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/moderation.py
> +import base_configs as configs
revert l'import

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/member.py
> +            prog_role = discord.utils.get(configs.PROG_ROLE)
tu devrais utilisé ça à la place: `guild.get_role(ROLE_ID)`

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/member.py
> +        former_student_count = 0
C'est vraiment juste un "best practice", mais normalement tu veux déclarer tes variables juste avant leur utilisation dans la mesure du possible

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/member.py
> +        # Get the guild object for the server you want to get the members from
FYI: C'est pas le serveur des membres que tu veux, mais le serveur d'où la commande à été utilisé

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/moderation.py
> +            raise commands.BadArgument(
revert ça aussi, pour éviter un "clash de formateur"

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/moderation.py
> +        moderation_embed = discord.Embed(
revert ça aussi, pour éviter un "clash de formateur"

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/moderation.py
> +        warn_embed = self.__create_moderation_embed(
revert ça aussi, pour éviter un "clash de formateur"

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/moderation.py
> +            raise permissions.InsufficientPermissionsError(
revert ça aussi, pour éviter un "clash de formateur"

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/moderation.py
> +            raise permissions.InsufficientPermissionsError(
revert ça aussi, pour éviter un "clash de formateur"

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/botcommands/moderation.py
> +            raise permissions.InsufficientPermissionsError(
revert ça aussi, pour éviter un "clash de formateur"

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/db/services/base_service.py
> +import base_configs as configs
revert l'import

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/interactions/errors.py
> +import base_configs as configs
revert l'import

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/interactions/errors.py
> +        super().__init__(
revert ça aussi, pour éviter un "clash de formateur"

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/interactions/ticket.py
> +import base_configs as configs
revert l'import

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/interactions/ticket.py
> +                                                view=TicketConfirmationInteraction(
revert ça aussi, pour éviter un "clash de formateur"

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/interactions/ticket.py
> +                                                view=TicketConfirmationInteraction(
revert ça aussi, pour éviter un "clash de formateur"

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/management/logging.py
> +import base_configs as configs
revert l'import

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/management/logging.py
> +        embed = discord.Embed(description=f"**Message modifié dans {after.channel.mention}** [Allez au message]({after.jump_url})",
revert ça aussi, pour éviter un "clash de formateur"

2022-12-31 01:40 UTC, DeveloperAnonymous commented on bot/management/logging.py
> +            embed.add_field(name="Contenu après",
revert ça aussi, pour éviter un "clash de formateur"

2023-01-02 10:33 UTC, Source-Dom commented
Je crois avoir tout corrigé 
et btw faudrait ajouter la commande dans !help, mais je sais pas c'est où.

2023-01-02 23:08 UTC, DeveloperAnonymous commented on bot/botcommands/member.py
> +        former_student_role = discord.utils.get(
T'as oublié de switch ce role là en guild.get_role() 😉

2023-01-02 23:10 UTC, DeveloperAnonymous commented
Looks good, reste juste un oublie, je te l'approve, mais merge après le changement

2023-01-02 23:11 UTC, DeveloperAnonymous submitted a review, later dismissed

2023-01-07 21:03 UTC, Zuyoutoki approved these changes

2023-01-07 21:11 UTC, DeveloperAnonymous approved these changes

2023-01-07 21:12 UTC, merged